# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json

# markdownlint configuration.

# For more information, see:
# https://github.com/DavidAnson/markdownlint#optionsconfig.

# Enable all rules.
default: true

line-length:
  # Line length checking is not strict by default.
  strict: true
  line_length: 120
  # Allow longer lines for code blocks.
  code_block_line_length: 100

# Do not always require language specifiers with fenced code blocks since they
# are not part of the Markdown spec.
fenced-code-language: false

# Allow <details> and <section> HTML elements
no-inline-html:
  allowed_elements: ['details', 'summary', 'a', 'br', 'div', 'h1', 'h2', 'p', 'strong', 'center']

# Due to feature to link back to top
first-line-h1: false
