/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers'
import type { IPollManagerACL, IPollManagerACLInterface } from '../../interfaces/IPollManagerACL'

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'in_dao',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'in_creator',
        type: 'address',
      },
    ],
    name: 'canCreatePoll',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export class IPollManagerACL__factory {
  static readonly abi = _abi
  static createInterface(): IPollManagerACLInterface {
    return new Interface(_abi) as IPollManagerACLInterface
  }
  static connect(address: string, runner?: ContractRunner | null): IPollManagerACL {
    return new Contract(address, _abi, runner) as unknown as IPollManagerACL
  }
}
