/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPollACL } from './IPollACL'
export type { IPollManager } from './IPollManager'
export type { IPollManagerACL } from './IPollManagerACL'
