# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-build

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches: [master]
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches: [master]

jobs:
  build:
    # NOTE: This name appears in GitHub's Checks API.
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Set workflow variables
        # Id is needed to access output in a next step.
        id: vars
        run: |
          echo "PNPM_CACHE_DIR=$(pnpm store path)" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.vars.outputs.PNPM_CACHE_DIR }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Build frontend app
        run: pnpm --filter @oasisprotocol/dapp-voting-frontend build
      - name: Upload frontend build artifacts
        # Upload build artifacts on push event.
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: oasis-voTEE-frontend-${{ steps.vars.outputs.SHORT_SHA }}
          path: frontend/dist
